services:
  postgres:
    image: postgres:latest
    container_name: nectar-postgres
    restart: always
    ports:
      - '5433:5432'
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    entrypoint: ['/bin/sh', '-c', 'rm -rf /var/run/postgresql/* && docker-entrypoint.sh postgres']
    networks:
      - shared

volumes:
  pgdata:

networks:
  shared:
    external: true
